// export const ACTION_NAME = "ACTION_NAME"
export const USER_LOADED = 'USER_LOADED',
export const USER_LOADING = 'USER_LOADING',
export const AUTH_ERROR = 'AUTH_ERROR',
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS',
export const LOGIN_FAIL = 'LOGIN_FAIL',
export const LOGOUY_SUCCESS = 'LOGOUY_SUCCESS',
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS',
export const REGISTER_FAIL = 'REGISTER_FAIL',